# render.yaml for deploying WhatsApp bot to Render.com
services:
  - type: web
    name: ben-whittaker-tech-bot
    env: node
    plan: starter
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: NODE_ENV
        value: production
      # Add other environment variables here if needed
      # - key: OWNER_JID
      #   value: "255760317060@s.whatsapp.net"
