services:
  - type: web
    name: ben-whittaker-tech-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    branch: main
    healthCheckPath: /
