services:
  - type: web
    name: ben-tech-pair-site
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: PORT
        value: "10000"   # Render usually sets PORT automatically, hii ni optional
    autoDeploy: true
